### PR TITLE
make days abbreviation like the native gnome calendar ones

### PR DESCRIPTION
**Pull request by burawi**
This PR aims to make the days' abbreviations like the ones in the native gnome calendar.

### CODE REVIEW

**Comment by omid** [comment]
Do you have any reference for this? I do not speak Arabic. But need a proof that they are how they call them.

**Comment by burawi** [comment]
Hey @omid 
Here is a screenshot from my gnome calendar in Arabic:
image

**Comment by omid** [comment]
Hey @burawi 
No no, I meant a wikipedia page or something, to show that abbr of weekdays in Arabic are so.

**Comment by nassimmiled** [comment]
@omid check this [link](https://support.microsoft.com/ar-sa/office/%D8%B9%D8%B1%D8%B6-%D8%AA%D9%82%D9%88%D9%8A%D9%85-%D8%A8%D8%AF%D9%8A%D9%84-8cb201d4-c175-4d9e-9d8f-b4df00ca8f82)  from Microsoft, shows the abbr of weekdays in Arabic 

image

**Comment by omid** [comment]
Thanks @nassimmiled 
So based on this, what we had was correct, and this PR should be rejected.

**Pull request closed without merging**
